---
- hosts: physical
  become: true
  roles:
    - base-config

- hosts: cloud
  become: true
  vars:
    - versions.yml
  roles:
    - microcloud

- hosts: auth_server
  become: true
  vars_files:
    - ldap-vars.yml
    - credentials-vault.yml
  roles:
    - ldap-server