---
- hosts: physical
  become: true
  vars_files:
    - vars.yml
    - encrypted-vars.yml
  roles:
    - base-config
    - artis3n.tailscale

- hosts: auth_server
  become: true
  vars_files:
    - vars.yml
    - encrypted-vars.yml
  roles:
    - ldap-server

- hosts: all
  become: true
  vars_files:
    - vars.yml
    - encrypted-vars.yml
  roles:
    - ldap-client

- hosts: cloud
  become: true
  vars_files:
    - vars.yml
    - encrypted-vars.yml
  roles:
    - microcloud
