---

roles:
  - name: artis3n.tailscale
    src: https://github.com/artis3n/ansible-role-tailscale
    version: main

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">7.0.0"
    source: https://galaxy.ansible.com
  - name: smallstep.cli
    source: https://galaxy.ansible.com