---
# tasks file for ldap-client

- name: Install packages
  ansible.builtin.package:
    name:
      - sssd-ldap
      - ldap-utils
    state: latest

- name: Check for ssl folder
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: ./ssl
  register: ssl_folder

- name: Generate sssd config
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Start and enable sssd
  ansible.builtin.systemd_service:
    name: sssd
    state: started
    enabled: true

- name: Enable mkhomedir
  ansible.builtin.command: pam-auth-update --enable mkhomedir --force

- name: Add arguments ot mkhomedir
  community.general.pamd:
    name: common-session
    type: session
    control: optional
    module_path: pam_mkhomedir.so
    module_arguments: skel=/etc/skel/ umask=0022
    state: args_present

- name: Setup sudoers
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers.d/sudoers
    owner: root
    group: root
    mode: u=r,g=r,o=

- name: Generate ldap client config
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy CA cert
  ansible.builtin.copy:
    src: ssl/chain.pem
    dest: /etc/ssl/certs/chain.pem
    owner: root
    group: root
    mode: u=rw,g=rw,o=r
  when: ssl_folder.stat.exists

- name: SSH Key search script
  ansible.builtin.copy:
    src: ldap-ssh-publickey.sh
    dest: /usr/local/bin/ldap-ssh-publickey.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Enable LDAP search for SSH Key
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^##AuthorizedKeysCommand'
    line: 'AuthorizedKeysCommand /usr/local/bin/ldap-ssh-publickey.sh'

- name: Enable LDAP search for SSH Key
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^##AuthorizedKeysCommandUser'
    line: 'AuthorizedKeysCommandUser nobody'

- name: Restart SSH
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
