---
# tasks file for ldap-client

- name: Install packages
  ansible.builtin.package:
    name:
      - sssd-ldap
      - ldap-utils
    state: latest

- name: Generate sssd config
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Start and enable sssd
  systemd_service:
    name: sssd
    state: started
    enabled: true

- name: Enable mkhomedir
  command: pam-auth-update --enable mkhomedir --force

- name: Add arguments ot mkhomedir
  pamd:
    name: common-session
    type: session
    control: optional
    module_path: pam_mkhomedir.so
    module_arguments: skel=/etc/skel/ umask=0022
    state: args_present

- name: Setup sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers.d/sudoers
    owner: root
    group: root
    mode: u=r,g=r,o=

- name: Generate ldap client config
  template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: SSH Key search script
  copy:
    src: ldap-ssh-publickey.sh
    dest: /usr/local/bin/ldap-ssh-publickey.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Enable LDAP search for SSH Key
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^##AuthorizedKeysCommand'
    line: 'AuthorizedKeysCommand /usr/local/bin/ldap-ssh-publickey.sh'

- name: Enable LDAP search for SSH Key
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^##AuthorizedKeysCommandUser'
    line: 'AuthorizedKeysCommandUser nobody'

- name: Restart SSH
  systemd_service:
    name: sshd
    state: restarted
