---
# tasks file for base-config

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Install core packages
  package:
    name:
      - zsh
      - squid-deb-proxy-client